apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cityvote-ingress
  namespace: cityvote
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/websocket-services: cityvote-service
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  rules:
  - host: cityvote.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cityvote-service
            port:
              number: 4321
