apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bugwars
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/KBVE/kbve
    targetRevision: HEAD
    path: apps/kube/bugwars/manifest
  destination:
    server: https://kubernetes.default.svc
    namespace: bugwars
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - RespectIgnoreDifferences=true
    - Replace=false
