apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: arc-controller-manifests
  annotations:
    description: "Additional manifests for ARC controller (secrets, RBAC for ExternalSecrets)"

resources:
  - sealed-github-arc-token.yaml
  - external-secrets-rbac.yaml
