version: 2

updates:
    - package-ecosystem: npm
      directory: /
      target-branch: dev
      schedule:
          interval: weekly
          day: monday
      open-pull-requests-limit: 5
      labels:
          - dependencies
          - npm
          - security
          - update

    - package-ecosystem: pip
      directory: /
      target-branch: dev
      schedule:
          interval: weekly
          day: monday
      open-pull-requests-limit: 3
      labels:
          - dependencies
          - python
          - security
          - update

    - package-ecosystem: cargo
      directory: /
      target-branch: dev
      schedule:
          interval: weekly
          day: monday
      open-pull-requests-limit: 3
      labels:
          - dependencies
          - rust
          - security
          - update

    - package-ecosystem: github-actions
      directory: /
      target-branch: dev
      schedule:
          interval: weekly
          day: monday
      open-pull-requests-limit: 5
      labels:
          - dependencies
          - ci
          - security
          - update

    - package-ecosystem: docker
      directory: /
      target-branch: dev
      schedule:
          interval: monthly
      open-pull-requests-limit: 3
      labels:
          - dependencies
          - docker
          - security
          - update
