[package]
name = "erust"
authors = ["kbve", "h0lybyte"]
version = "0.1.3"
edition = "2021"
license = "MIT"
description = "ERust is an additional package for egui and eframe that provides extendable components."
homepage = "https://kbve.com/"
repository = "https://github.com/kbve/kbve/"
readme = "README.md"
rust-version = "1.75"


[dependencies]
base64 = "0.21.6"
egui = "0.25.0"
eframe = { version = "0.25.0", default-features = false, features = [
    "accesskit",     # Make egui comptaible with screen readers. NOTE: adds a lot of dependencies.
    "default_fonts", # Embed the default egui fonts.
    "glow",          # Use the glow rendering backend. Alternative: "wgpu".
    "persistence",   # Enable restoring app state when restarting the app.
] }
log = "0.4"
ehttp = "0.3.1"
image = "0.24.7"

chrono = { version = "0.4.24", features = ["serde"] }

serde = { version = "1", features = ["derive"] }
serde_json = "1.0"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4"
