apiVersion: v1
kind: Service
metadata:
    name: mc-service
    namespace: mc
    labels:
        app: mc
    annotations:
        metallb.universe.tf/allow-shared-ip: 'shared-public-ip'
spec:
    type: LoadBalancer
    selector:
        app: mc
    ports:
        - name: java
          port: 25565
          targetPort: 25565
          protocol: TCP
        - name: bedrock
          port: 19132
          targetPort: 19132
          protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
    name: mc-internal-service
    namespace: mc
    labels:
        app: mc
spec:
    type: ClusterIP
    selector:
        app: mc
    ports:
        - name: resource-pack
          port: 8080
          targetPort: 8080
          protocol: TCP
        - name: rcon
          port: 25575
          targetPort: 25575
          protocol: TCP
