#[unstable]
#build-std = ["std"]

[target.wasm32-unknown-emscripten]
rustflags = [
    "-C", "link-args=-sSIDE_MODULE=2",
    "-C", "link-args=-pthread", # was -sUSE_PTHREADS=1 in earlier emscripten versions
    "-C", "target-feature=+atomics,+bulk-memory,+mutable-globals",
    "-Z", "link-native-libraries=no",
    "-C", "link-arg=-fwasm-exceptions",
    "-C", "link-args=-sSUPPORT_LONGJMP=wasm",
    "-C", "llvm-args=-enable-emscripten-cxx-exceptions=0",
    "-C", "llvm-args=-wasm-enable-sjlj",
    "-C", "link-args=-sDISABLE_EXCEPTION_CATCHING=1",
]

#[build]
#target = ["wasm32-unknown-emscripten"]