blank_issues_enabled: false
contact_links:
  - name: Ask us on Discord!?
    url: https://kbve.com/discord/
    about: Join the Discord and give us your suggestions
  - name: Contact Us via Support Ticket!?
    url: https://kbve.com/support/
    about: Visit our content us page and open a support ticket it!