[package]
name = "holy"
authors = ["kbve", "h0lybyte"]
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "Holy is a proc-macro library that provides helper macros."
homepage = "https://kbve.com/"
repository = "https://github.com/KBVE/kbve/tree/main/packages/holy"
readme = "README.md"
rust-version = "1.75"

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
