apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: memes

resources:
  - memes-serviceaccount.yaml
  - memes-externalsecret.yaml
  - memes-deployment.yaml
  - nginx-ingress.yaml
