apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: memes-ingress
  namespace: memes
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: meme.sh
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: memes-service
            port:
              number: 4321
  - host: www.meme.sh
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: memes-service
            port:
              number: 4321
