apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
    name: public-ip-pool
    namespace: metallb-system
spec:
    addresses:
        - 142.132.206.74/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
    name: public-l2
    namespace: metallb-system
