apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kbve-ingress
  namespace: kbve
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: kbve.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kbve-service
            port:
              number: 4321