[package]
name = "q"
authors = ["kbve", "h0lybyte"]
version = "0.1.1"
edition = "2024"
license = "MIT"
description = "Q is a Rust GDExtension crate for Godot, offering a Game Manager, Music Manager, Bevy ECS, and Tokio-powered multi-threading. It simplifies and enhances game development with efficient tools and scalable performance."
homepage = "https://kbve.com/application/rust/"
repository = "https://github.com/KBVE/kbve/tree/main/packages/erust"
readme = "README.md"
rust-version = "1.85"
exclude = [
    "release/*",
    "docs/*",
]

[lib]
crate-type = ["cdylib"]

[dependencies]
rand = "0.9.2"
godot = { version = "0.3.5", features = ["experimental-wasm", "experimental-threads"] }
bevy_ecs = { version = "0.15.1", features = ["default"] }
rstar = "0.12.2"
papaya = "0.2.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bitflags = { version = "2.9.0", features = ["serde"] }


[target."cfg(target_os = \"macos\")".dependencies]
objc2 = "0.6.3"
wry = { version = "0.53.5", features = ["transparent", "devtools"] }
raw-window-handle = "0.6.2"
http = "1.1.0"
infer = "0.19.0"
tokio = { version = "1.49", features = ["full", "rt-multi-thread"] }


[target."cfg(target_os = \"windows\")".dependencies]
windows = { version = "0.62", features = [
    "Data_Xml_Dom",
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",
] }
wry = { version = "0.53.5", features = ["transparent", "devtools"] }
raw-window-handle = "0.6.2"
http = "1.1.0"
infer = "0.19.0"
tokio = { version = "1.49", features = ["full", "rt-multi-thread"] }


[profile.release]
opt-level = 'z'
lto = "fat"
codegen-units = 1
debug = false
