[package]
name = "q"
authors = ["kbve", "h0lybyte"]
version = "0.1.1"
edition = "2024"
license = "MIT"
description = "Q is a Rust GDExtension crate for Godot, offering a Game Manager, Music Manager, Bevy ECS, and Tokio-powered multi-threading. It simplifies and enhances game development with efficient tools and scalable performance."
homepage = "https://kbve.com/application/rust/"
repository = "https://github.com/KBVE/kbve/tree/main/packages/rust/q"
readme = "README.md"
rust-version = "1.88"
exclude = [
    "release/*",
    "docs/*",
]

[lib]
crate-type = ["cdylib"]

[dependencies]
rand = "0.10.0"
godot = { version = "0.4.5", features = ["experimental-wasm", "experimental-threads"] }
dashmap = "6.1.0"
crossbeam-channel = "0.5.15"
ulid = "1.2.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bitflags = { version = "2.9.0", features = ["serde"] }


[target."cfg(target_os = \"macos\")".dependencies]
objc2 = "0.6.3"
wry = { version = "0.54.2", features = ["transparent", "devtools"] }
raw-window-handle = "0.6.2"
http = "1.4.0"
infer = "0.19.0"
tokio = { version = "1.49", features = ["full", "rt-multi-thread"] }


[target."cfg(target_os = \"windows\")".dependencies]
windows = { version = "0.62.2", features = [
    "Data_Xml_Dom",
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",
] }
wry = { version = "0.54.2", features = ["transparent", "devtools"] }
raw-window-handle = "0.6.2"
http = "1.4.0"
infer = "0.19.0"
tokio = { version = "1.49", features = ["full", "rt-multi-thread"] }


[target."cfg(target_os = \"linux\")".dependencies]
wry = { version = "0.54.2", features = ["transparent", "devtools"] }
raw-window-handle = "0.6.2"
http = "1.4.0"
infer = "0.19.0"
tokio = { version = "1.49", features = ["full", "rt-multi-thread"] }


[profile.release]
opt-level = 'z'
lto = "fat"
codegen-units = 1
debug = false
