apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bugwars

resources:
  - bugwars-rbac.yaml
  - bugwars-externalsecret.yaml
  - bugwars-deployment.yaml
  - nginx-ingress.yaml
