apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bugwars-ingress
  namespace: bugwars
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/websocket-services: bugwars-service
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/upstream-hash-by: "$http_upgrade"
    nginx.ingress.kubernetes.io/proxy-pass-headers: "Cross-Origin-Opener-Policy,Cross-Origin-Embedder-Policy,Cross-Origin-Resource-Policy"
spec:
  rules:
  - host: bugwars.kbve.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bugwars-service
            port:
              number: 4321
