[package]
name = "holy"
authors = ["kbve", "h0lybyte"]
version = "0.2.0"
edition = "2024"
license = "MIT"
description = "Holy is a proc-macro library that provides helper macros."
homepage = "https://kbve.com/"
repository = "https://github.com/KBVE/kbve/tree/main/packages/rust/holy"
readme = "README.md"
rust-version = "1.85"

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0.44"
proc-macro2 = "1.0"

[dev-dependencies]
trybuild = "1.0"
rand = "0.8"

[lib]
proc-macro = true
