apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rentearth

resources:
    - rentearth-serviceaccount.yaml
    - rentearth-externalsecret.yaml
    - rentearth-deployment.yaml
    - nginx-ingress.yaml
