apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: herbmail

resources:
  - herbmail-serviceaccount.yaml
  - herbmail-externalsecret.yaml
  - herbmail-deployment.yaml
  - nginx-ingress.yaml
