apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: herbmail-ingress
  namespace: herbmail
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: herbmail.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: herbmail-service
            port:
              number: 4321
  - host: www.herbmail.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: herbmail-service
            port:
              number: 4321
