[package]
name = "kbve"
authors = ["kbve", "h0lybyte"]
version = "0.1.26"
edition = "2021"
license = "MIT"
description = "KBVE is an Axum and Diesel Boilerplate that helps produce backend APIs for micro services."
homepage = "https://kbve.com/"
repository = "https://github.com/KBVE/kbve/tree/main/packages/rust/kbve"
readme = "README.md"
rust-version = "1.78"

[features]
default = []
supabase = []

[dependencies]
anyhow = "1.0"
ammonia = "4.0.0"
argon2 = "0.5.0"
askama = "0.15.4"
async-trait = "0.1.74"
chrono = { version = "0.4.24", features = ["serde"] }
diesel = { version = "2.0.0", features = [
    "postgres",
    "chrono",
    "r2d2",
    "serde_json",
] }
dotenvy = "0.15"
axum = { version = "0.8.5", features = ["macros"] }
axum-extra = { version = "0.12.1", features = ["cookie"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dashmap = { version = "6.1.0", features = ["serde"] }
jsonwebtoken = "8.3.0"
rand_core = { version = "0.6.4", features = ["std"] }
tokio = { version = "1.0", features = ["full"] }
thiserror = "2"
time = "0.3.36"
reqwest = { version = "0.12", default-features = false, features = [
    "json",
    "rustls-tls",
] }
tower = { version = "0.5.3", features = ["timeout"] }
tower-http = { version = "0.6.8", features = ["cors"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
r2d2 = "0.8.9"
regex = "1.10.2"
once_cell = "1"
ulid = "1.1.0"
num-bigint = "0.4"
jedi = { path = "../jedi" }

[package.metadata.askama]
dirs = ["templates"]
