[package]
name = "jedi"
authors = ["kbve", "h0lybyte"]
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "Jedi is the Juggernaut Electronic Data Interchange package. This library provides a data exchange layer extended through the holy crate."
homepage = "https://kbve.com/"
repository = "https://github.com/KBVE/kbve/tree/main/packages/jedi"
readme = "README.md"
rust-version = "1.75"


[dependencies]
async-trait = "0.1.77"
dashmap = { version = "5.5.3", features = ["serde"] }
ammonia = "3.3.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
regex = "1.10.3"
once_cell = "1.19.0"
thiserror = "1.0.56"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
