apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: arc-runners-manifests
  annotations:
    description: "ExternalSecret to pull GitHub PAT from arc-systems namespace"

resources:
  - github-arc-externalsecret.yaml
  - runner-cache-pvc.yaml
